name       : python-idna_ssl
version    : 1.1.0
release    : 1
source     :
    - https://github.com/aio-libs/idna-ssl/archive/v1.1.0.tar.gz : cdbefa2429a6a2fa5cbe8d2a47c677ca671e84531618d3460fc0bcfc840684c5
license    : MIT
component  : programming.python
summary    : Patch ssl.match_hostname for Unicode(idna) domains support
description: |
    Patch ssl.match_hostname for Unicode(idna) domains support
builddeps  :
    - python-idna
rundeps    :
    - python-idna
build      : |
    %python3_setup
install    : |
    %python3_install
